[tools]
ast-grep = "0.40.5"
bat = "0.26.1"
"pipx:tldr" = "3.4.4"
bottom = "0.12.3"
cargo-binstall = "1.17.5"
"github:tummychow/git-absorb" = "0.9.0"
delta = "0.18.2"
difftastic = { version = "0.67.0", exe = "difft" }
fd = "10.3.0"
"gem:tmuxinator" = "3.3.7"
github-cli = "2.86.0"
go = "1.26.0"
jq = "1.8.1"
just = "1.46.0"
lazydocker = "0.24.4"
lazygit = "0.59.0"
maven = "3.9.12"
neovim = "0.11.6"
node = "25.6.1"
"pipx:basedpyright" = "1.38.0"
postgres = "16.4"
pre-commit = "4.5.1"
python = "3.13.11"
restic = "0.18.1"
ripgrep = "15.1.0"
ruby = "4.0.1"
ruff = "0.15.1"
rust = "1.93.1"
tree-sitter = "0.26.5"
usage = "2.17.0"
uv = "0.10.3"
yazi = "26.1.22"
yq = "4.52.4"
jj = "0.38.0"
jjui = "0.9.11"
zellij = "0.43.1"
zoxide = "0.9.9"
fzf = "0.67.0"
yamllint = "1.38.0"
yamlfmt = "0.21.0"
hadolint = "2.14.0"
"npm:dockerfile-language-server-nodejs" = "0.15.0"
"npm:@microsoft/compose-language-service" = "0.5.0"
"npm:@vtsls/language-server" = "0.3.0"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:@fsouza/prettierd" = "0.27.0"
"pipx:gitlint-core" = { version = "0.19.1", uvx_args = "--with gitlint" }
"pipx:sqlfluff" = "4.0.4"
"npm:yaml-language-server" = "1.20.0"
"pipx:mdformat" = "1.0.0"
rust-analyzer = "2026-02-16"
shellcheck = "0.11.0"
shfmt = "3.12.0"
"npm:markuplint" = "4.14.1"
marksman = "2026-02-08"
lua-language-server = "3.17.1"
"npm:sql-formatter" = "15.7.1"
"npm:stylelint" = "17.3.0"
stylua = "2.3.1"
taplo = { version = "0.10.0", matching = "full" }
"github:Myriad-Dreamin/tinymist" = "0.14.10"
"npm:vim-language-server" = "2.3.1"
"pipx:vim-vint" = "0.3.21"
"npm:@vue/language-server" = "3.2.4"
"npm:htmlhint" = "1.9.1"
"npm:bash-language-server" = "5.6.0"
"npm:awk-language-server" = "0.10.6"
"pipx:djlint" = "1.36.4"
"npm:markdownlint-cli" = "0.47.0"
"github:ribru17/ts_query_ls" = "3.15.1"
"cargo:just-lsp" = "0.3.3"
"npm:intelephense" = "1.16.5"
"github:supabase-community/postgres-language-server" = { version = "0.21.0", rename_exe = "postgrestools" }
"pipx:sqruff" = "0.34.1"
duckdb = "1.4.4"
hyperfine = "1.20.0"
"pipx:llm" = { version = "0.28", uvx_args = "--with llm-fragments-github --with llm-anthropic --with llm-gemini --with llm-commit --with llm-templates-fabric --with llm-hacker-news --with llm-fragments-pdf --with pymupdf-layout --with llm-docs" }
dive = "0.13.1"
xh = "0.25.3"
dust = "1.2.4"
"cargo:tokei" = "14.0.0"
"http:ncdu" = { url = "https://dev.yorhel.nl/download/ncdu-2.9.1-linux-x86_64.tar.gz", version = "2.9.1" }
"github:psviderski/unregistry" = { version = "0.4.1", exe = "docker-pussh" }
"npm:mcp-hub" = "4.2.1"
"cargo:ncspot" = "1.3.3"
"github:garethgeorge/backrest" = "1.11.2"
"pipx:vectorcode" = { version = "0.7.20", extras = "mcp,lsp" }
"cargo:bandwhich" = "0.23.1"
"cargo:inlyne" = "0.5.0"
claude-code = "2.1.44"
"github:jorgerojas26/lazysql" = "0.4.6"
gemini-cli = "0.28.2"
git-lfs = "3.7.1"
"cargo:presenterm" = "0.16.0"
"github:opentofu/tofu-ls" = "0.3.1"
"github:bitwarden/sdk-sm" = { version = "2.0.0", version_prefix = "bws-v" }
fnox = "1.12.1"
age = "1.3.1"
git-cliff = "2.12.0"
"cargo:forgejo-cli" = "0.4.0"
"pipx:ansible" = { version = "13.3.0", uvx_args = "--with-executables-from ansible-core --with-executables-from ansible-dev-tools --with-executables-from ansible-lint --with docker" }
"npm:@ansible/ansible-language-server" = "1.2.3"
fx = "39.2.0"

[settings]
experimental = true

[settings.python]
compile = true
uv_venv_create_args = ['--seed']
