[tools]
ast-grep = "0.40.3"
bat = "0.26.1"
"pipx:tldr" = "3.4.3"
bottom = "0.11.4"
cargo-binstall = "1.16.4"
"ubi:tummychow/git-absorb" = "0.8.0"
delta = "0.18.2"
difftastic = { version = "0.67.0", exe = "difft" }
fd = "10.3.0"
"gem:tmuxinator" = "3.3.7"
github-cli = "2.83.2"
go = "1.25.5"
jq = "1.8.1"
just = "1.45.0"
lazydocker = "0.24.2"
lazygit = "0.57.0"
maven = "3.9.12"
neovim = "0.11.5"
node = "25.2.1"
"pipx:basedpyright" = "1.36.1"
postgres = "16.4"
pre-commit = "4.5.1"
python = "3.13.11"
restic = "0.18.1"
ripgrep = "15.1.0"
ruby = "3.4.8"
ruff = "0.14.9"
rust = "1.92.0"
tree-sitter = "0.26.3"
usage = "2.9.0"
uv = "0.9.18"
yazi = "25.5.31"
yq = "4.50.1"
jj = "0.36.0"
jjui = "0.9.8"
zellij = "0.43.1"
zoxide = "0.9.8"
fzf = "0.67.0"
yamllint = "1.37.1"
yamlfmt = "0.20.0"
hadolint = "2.14.0"
"npm:dockerfile-language-server-nodejs" = "0.15.0"
"npm:@microsoft/compose-language-service" = "0.4.0"
"npm:@vtsls/language-server" = "0.2.9"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:@fsouza/prettierd" = "0.26.2"
"pipx:gitlint-core" = { version = "0.19.1", uvx_args = "--with gitlint" }
"pipx:sqlfluff" = "3.5.0"
"npm:yaml-language-server" = "1.19.2"
"pipx:mdformat" = "1.0.0"
rust-analyzer = "2025-12-15"
shellcheck = "0.11.0"
shfmt = "3.12.0"
"npm:markuplint" = "4.14.0"
marksman = "2025-12-13"
lua-language-server = "3.16.2"
"npm:sql-formatter" = "15.6.12"
"npm:stylelint" = "16.26.1"
stylua = "2.3.1"
taplo = { version = "0.10.0", matching = "full" }
"ubi:Myriad-Dreamin/tinymist" = "0.14.4"
"npm:vim-language-server" = "2.3.1"
"pipx:vim-vint" = "0.3.21"
"npm:@vue/language-server" = "3.2.0"
"npm:htmlhint" = "1.8.0"
"npm:bash-language-server" = "5.6.0"
"npm:awk-language-server" = "0.10.6"
"pipx:djlint" = "1.36.4"
"npm:markdownlint-cli" = "0.47.0"
"ubi:ribru17/ts_query_ls" = "3.14.0"
"cargo:just-lsp" = "0.2.8"
"npm:intelephense" = "1.16.3"
"ubi:supabase-community/postgres-language-server" = { version = "0.18.0", rename_exe = "postgrestools" }
"pipx:sqruff" = "0.29.3"
duckdb = "1.4.3"
hyperfine = "1.20.0"
"pipx:llm" = { version = "0.28", uvx_args = "--with llm-fragments-github --with llm-anthropic --with llm-github-copilot --with llm-commit --with llm-templates-fabric --with llm-hacker-news --with llm-fragments-pdf --with llm-docs" }
dive = "0.13.1"
xh = "0.25.3"
dust = "1.2.3"
"cargo:tokei" = "13.0.0"
"http:ncdu" = { url = "https://dev.yorhel.nl/download/ncdu-2.9.1-linux-x86_64.tar.gz", version = "2.9.1" }
"github:psviderski/unregistry" = { version = "0.4.1", exe = "docker-pussh" }
"npm:mcp-hub" = "4.2.1"
"cargo:ncspot" = "latest"
"github:garethgeorge/backrest" = "1.10.1"
"pipx:vectorcode" = { version = "0.7.20", extras = "mcp,lsp" }
"cargo:bandwhich" = "0.23.1"
"cargo:inlyne" = "0.5.0"
"npm:@anthropic-ai/claude-code" = "2.0.74"
"github:jorgerojas26/lazysql" = "0.4.5"
gemini-cli = "0.21.3"
git-lfs = "3.7.1"
"cargo:presenterm" = "0.15.1"

[tool_alias.bitwarden-secrets-manager.versions]
"1.0.0" = "bws-v1.0.0"

[settings]
experimental = true

[settings.python]
compile = true
uv_venv_create_args = ['--seed']
