[tools]
ast-grep = "0.39.7"
bat = "0.26.0"
"pipx:tldr" = "3.4.3"
bottom = "0.11.2"
cargo-binstall = "1.15.10"
"ubi:tummychow/git-absorb" = "0.8.0"
delta = "0.18.2"
difftastic = { version = "0.65.0", exe = "difft" }
direnv = "2.37.1"
fd = "10.3.0"
"gem:tmuxinator" = "3.3.5"
github-cli = "2.83.0"
go = "1.25.4"
jq = "1.8.1"
just = "1.43.0"
lazydocker = "0.24.1"
lazygit = "0.56.0"
maven = "3.9.9"
neovim = "0.11.5"
node = "25.1.0"
"pipx:basedpyright" = "1.32.1"
postgres = "16.4"
pre-commit = "4.3.0"
python = "3.13.8"
restic = "0.18.1"
ripgrep = "15.1.0"
ruby = "3.4.7"
ruff = "0.14.3"
rust = "1.91.0"
tree-sitter = "0.25.10"
usage = "2.6.0"
uv = "0.9.7"
yazi = "25.5.31"
yq = "4.48.1"
jj = "0.34.0"
jjui = "0.9.5"
zellij = "0.43.1"
zoxide = "0.9.8"
fzf = "0.66.1"
yamllint = "1.37.1"
yamlfmt = "0.20.0"
hadolint = "2.14.0"
"npm:dockerfile-language-server-nodejs" = "0.15.0"
"npm:@microsoft/compose-language-service" = "0.4.0"
"npm:@vtsls/language-server" = "0.2.9"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:@fsouza/prettierd" = "0.26.2"
"pipx:gitlint-core" = { version = "0.19.1", uvx_args = "--with gitlint" }
"pipx:sqlfluff" = "3.5.0"
"npm:yaml-language-server" = "1.19.2"
"pipx:mdformat" = "1.0.0"
rust-analyzer = "2025-10-28"
shellcheck = "0.11.0"
shfmt = "3.12.0"
"npm:markuplint" = "4.13.1"
marksman = "2024-12-18"
lua-language-server = "3.15.0"
"npm:sql-formatter" = "15.6.10"
"npm:stylelint" = "16.25.0"
stylua = "2.3.1"
taplo = { version = "0.10.0", matching = "full" }
"ubi:Myriad-Dreamin/tinymist" = "0.14.0"
"npm:vim-language-server" = "2.3.1"
"pipx:vim-vint" = "0.3.21"
"npm:@vue/language-server" = "3.1.2"
"npm:htmlhint" = "1.7.1"
"npm:bash-language-server" = "5.6.0"
"npm:awk-language-server" = "0.10.6"
"pipx:djlint" = "1.36.4"
"npm:markdownlint-cli" = "0.45.0"
"ubi:ribru17/ts_query_ls" = "3.11.1"
"cargo:just-lsp" = "0.2.7"
"npm:intelephense" = "1.14.4"
"ubi:supabase-community/postgres-language-server" = { version = "0.17.2", rename_exe = "postgrestools" }
"pipx:sqruff" = "0.29.3"
duckdb = "1.4.1"
hyperfine = "1.19.0"
"pipx:llm" = { version = "0.27.1", uvx_args = "--with llm-fragments-github --with llm-anthropic --with llm-github-copilot --with llm-commit --with llm-templates-fabric --with llm-hacker-news --with llm-fragments-pdf --with llm-docs" }
dive = "0.13.1"
xh = "0.25.0"
dust = "1.2.3"
tokei = "12.1.2"
"http:ncdu" = { url = "https://dev.yorhel.nl/download/ncdu-2.9.1-linux-x86_64.tar.gz", version = "2.9.1" }
"ubi:https://github.com/psviderski/unregistry/archive/refs/tags/v0.3.1.tar.gz" = { version = "v0.3.1", exe = "docker-pussh" }
"npm:mcp-hub" = "4.2.1"
"cargo:ncspot" = "latest"
"github:garethgeorge/backrest" = "1.10.1"
"pipx:vectorcode" = { version = "0.7.18", extras = "mcp,lsp" }
"cargo:bandwhich" = "0.23.1"
"cargo:inlyne" = "0.5.0"
"npm:@anthropic-ai/claude-code" = "2.0.31"
"github:jorgerojas26/lazysql" = "0.4.3"
gemini-cli = "0.11.3"
git-lfs = "3.7.1"

[alias.bitwarden-secrets-manager.versions]
"1.0.0" = "bws-v1.0.0"

[settings]
experimental = true

[settings.python]
compile = true
