---
git:
  autoForwardBranches: none
gui:
  showDivergenceFromBaseBranch: arrowAndNumber
keybinding:
  universal:
    suspendApp: <disabled>
    redo: <c-z>
customCommands:
  - key: '<c-v>'
    context: 'files'
    command: git diff --staged | llm -t conventional-commit | git commit -e -F -
    description: 'Commit with AI'
    output: terminal
